### PR TITLE
fix/json-path - adding null check

### LINKED ISSUE #281: json-path -> patch: TypeError: Cannot read property of null
Hello,
This happens in `v2.0.0`, but not in `1.0.0` (I discovered the issue after upgrading). The culprit seems to be the `patch` function in the `record/json-path.js` module, and the issue seems to have been introduced in [this commit](https://github.com/deepstreamIO/deepstream.io-client-js/commit/f687485a420b77e9d1922e6032f4b3524dab042b).

My particular case is kinda complex, but debugging the client it seems that this exception gets thrown when `patch` is called by  `set` and a value lower in the tree goes from falsy (or possibly even non-object) to object. 

In my case, `oldValue` is descended recursively in patch, until it gets to a sub-object of the form:

**oldValue**
```javascript
{
  job: null,
  joinedAt: 1480020987915
}
```

**newValue**
```javascript
{
  job: { id: 88 },
  joinedAt: 1480020987915
}
```

**deepCopy**
```javascript
true
```

At this point, `patch` is recursively called with the `job` sub-object, and the arguments are:

**oldValue**
```javascript
null
```

**newValue**
```javascript
{ id: 88 }
```

**deepCopy**
```javascript
true
```

This makes the client crash with an exception, when [this line](https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/json-path.js#L97) is executed:

```javascript
obj[ props[ i ] ] = patch( oldValue[ props[ i ] ], newValue[ props[ i ] ], deepCopy )
```

Since `props` is the keys of `newValue`, this will try to compute `oldValue.id`. But `oldValue` is `null` and an exception gets thrown. It seems that an additional check for this (pretty common) case is needed in `patch`.

### PR DESCRIPTION
**Pull request by AlexBHarley**
Fixes #281 - unit tests to follow

### CODE REVIEW

File: src/record/json-path.js [hunk 1]
```diff
@@ -83,6 +83,9 @@ function patch( oldValue, newValue, deepCopy ) {
 	if ( utils.deepEquals( oldValue, newValue ) ) {
 		return oldValue;
 	}
+	else if ( oldValue === null || newValue === null ) {
```
Comment (yasserf) [inline src/record/json-path.js]: No related test? (A)
