### PR TITLE
Bug/nested change doesnt trigger general subscribe

### LINKED ISSUE #78: record.subscribe without a path doesn't trigger for changes to nested objects
The problem is that `record._beginChange` uses `record.get` to retrieve `this._oldValue`, but `record.get` only uses `utils.shallowCopy`. Therefor `utils.deepEquals( this._oldValue, this._$data )` in `record._completeChange` returns true and the listeners are not notified.

I'll change it to deepCopy records. This is less performant, but also prevents hard to diagnose bugs such as unconsciously manipulating deepstream's internal values.

### PR DESCRIPTION
**Pull request by WolframHempel**
FIXES #78

### CODE REVIEW

File: src/utils/utils.js [hunk 1]
```diff
@@ -1,88 +1,112 @@
...
 
+/**
+ * True if environment is node, false if it's a browser
+ * This seems somewhat inelegant, if anyone knows a better solution,
+ * let's change this (must identify browserify's pseudo node implementation though)
+ *
+ * @public
+ * @type {Boolean}
+ */
+exports.isNode = typeof process !== 'undefined' && process.toString() === '[object process]';
```
Comment (WolframHempel) [inline src/utils/utils.js]: Explanation: Didn't need to be a function that's evaluated everytime nextTick is called

File: src/utils/utils.js [hunk 2]
```diff
@@ -1,88 +1,112 @@
...
+ *
+ * @public
+ * @returns {String} trimmedString
+ */
 exports.trim = function( inputString ) {
 	if( inputString.trim ) {
 		return inputString.trim();
 	} else {
-		return inputString.replace( trimRegExp, '' );
+		return inputString.replace( TRIM_REGULAR_EXPRESSION, '' );
```
Comment (yasserf) [inline src/utils/utils.js]: Is this quicker than .trim()?

File: src/utils/utils.js [hunk 3]
```diff
@@ -1,88 +1,112 @@
...
-exports.deepEquals = function( objA, objB ) {
-	var isEqual = true, 
-		next;
-
-	if( objA === null || objB === null ) {
-		return objA === objB;
-	}
-
+/**
+ * Compares two objects for deep (recoursive) equality
```
Comment (yasserf) [inline src/utils/utils.js]: Recursive?

File: src/utils/utils.js [hunk 4]
```diff
@@ -1,88 +1,112 @@
...
+ * @param   {Mixed} objB
+ *
+ * @public
+ * @returns {Boolean} isEqual
+ */
+exports.deepEquals= function( objA, objB ) {
 	if( typeof objA !== OBJECT || typeof objB !== OBJECT ) {
 		return objA === objB;
+	} else {
+		return JSON.stringify( objA ) === JSON.stringify( objB );
```
Comment (yasserf) [inline src/utils/utils.js]: I like, was thinking this would be a good approach too.

It doesnt copy over functions though, and I'm not sure about date objects ( on phone now so can't test )

File: src/utils/utils.js (hunk 2 above)
Comment (WolframHempel) [inline src/utils/utils.js]: It's a polyfill for trim (see line 52/53) the only change is that I renamed the variable

File: src/utils/utils.js (hunk 3 above)
Comment (WolframHempel) [inline src/utils/utils.js]: ah, is that not the British spelling (as in colour and honour?)

File: src/utils/utils.js (hunk 4 above)
Comment (WolframHempel) [inline src/utils/utils.js]: You're right, tt doesn't, but it is only used to clone record data which is serializable anyways

File: src/utils/utils.js (hunk 2 above)
Comment (yasserf) [inline src/utils/utils.js]: Ah my bad, didn't realise. Didn't know that trim was something new/ish

File: src/utils/utils.js (hunk 4 above)
Comment (yasserf) [inline src/utils/utils.js]: agreed, but is it worth mentioning as well in docs? I'm happy eitherways ( also, this comment was meant to be for deepClone method )
