### PR TITLE
[task] do not depend on browser or nodejs URL api [fix] export DeepstreamClient as object property in bundle

### LINKED ISSUE #515: React Native 0.59+ URLSearchParams 'Error: not implemented'
Hi, i am trying to upgrade deepstream js client to v4, on React Native 0.61 but application seems to fail on this line of code:
` const client = new DeepstreamClient(url)`

because on `pareseUrl` it is calling `URL.host` and reaches the following code that throws an exception: 
https://github.com/facebook/react-native/blob/e6057095adfdc77ccbbff1c97b1e86b06dae340b/Libraries/Blob/URL.js#L157-L159

Capture

Also i get this warning when removing the validation buy it might be another issue not related to this one
Capture

I've  tried solutions described here [[0.59.x] URLSearchParams 'Error: not implemented'](https://github.com/facebook/react-native/issues/23922) but nothing seems to work.
Note: Client version 2.3.4 seems to work fine.

Is there any chance to support deepstream client **v4**+ on React Native **v0.59**+ ?
My dependencies are:
```
"react": "16.9.0",
"react-native": "0.61.2",
"@deepstream/client": "^4.1.3",
"url": "^0.11.0"
```

### PR DESCRIPTION
**Pull request by jaime-ez**
Hi @yasserf, hope everything is ok.

I gave a second thought to the react-native issue and chose not to use the URL api, neither from the browser nor nodejs, since the use case is rather simple, and coded the url string manipulation directly. This allows to use the client in web, nodejs and react-native without adding more external dependencies. This fixes #515

Also exported the client as object in order to maintain the same api in the bundle. This fixes issue #528 

Let me know what you think and I can push the package and changelog updates.

Also, should the main file in the package.json point to the bundle?

Cheers

### CODE REVIEW

**Comment by jaime-ez** [comment]
The explicit Buffer import made in the last commit fixes #529

**Comment by yasserf** [comment]
Seems good to me. Happy to merge this in and you can commit changelog and tag directly from master. Thanks!

**Comment by jaime-ez** [comment]
Ok, just did it...could you build and publish it to npm?
Best

**Comment by jaime-ez** [comment]
@yasserf sorry to bother, I forgot to change the main file on package.json, in order to make it work on react-native it must be one of the bundle files, since the Buffer module is not available otherwise, so I'll put the minified one and make a new push.

One question though: since the main file on package.json is changing, the new version should be 5.1.2 or 5.2.0 ?

File: src/connection/socket-factory.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import { Buffer } from 'buffer'
```
Comment (yasserf) [inline src/connection/socket-factory.ts:1]: why is this needed btw? Is it not polyfilled?

**Comment by yasserf** [comment]
@jaime-ez you can push the tag `v5.1.2` and it should auto publish btw. CI systems yay.

I don't think changing the package.json main file makes a difference in semantic versioning since noone really uses it outside of npm (that I know of, if they do it's a bit odd and we have a small enough pool of users for it to be very unlikely).
