### PR TITLE
Fixes #27 anonymous record ready event

### LINKED ISSUE #27: Force disconnect/login a client that is connected
We have an Android application that is showing our web-application in a web view (we're using Crosswalk's webview, https://crosswalk-project.org/). When the application is loosing its focus (i.e. the user minimizes the application) we need to disconnect our socket, and when the application is regaining its focus we need to login with the socket again. Or is this the wrong way to do it?

We know when the application is loosing focus and when it's regaining focus.

We've tried to close the socket (with `deepstreamClient.close()`), and then login with it again. However, this gives us the error: `this client's connection was closed`, which is wanted since we actually closed the socket.

What we would need is a `deepstreamClient.disconnect()` or some kind of re-login on the current socket.

Is this possible to implement?
I can make a PR if I could get some hints where do add this functionality so you guys don't have to implement this =)

### PR DESCRIPTION
**Pull request by yasserf**

### CODE REVIEW

File: test-e2e/specs/anonymous-recordSpec.js [hunk 1]
```diff
@@ -53,21 +53,21 @@ describe( 'anonymous record', function() {
...
-        }, 20);
+        });
+        anonymousRecord.setName( 'recordA' );
     });
     
     it( 'sets recordB', function(done) {
-        anonymousRecord.setName( 'recordB' );
-        setTimeout(function(){
-            expect( currentPet ).toBe( 'pug' );
+        anonymousRecord.once( 'ready', function(){
```
Comment (WolframHempel) [inline test-e2e/specs/anonymous-recordSpec.js]: Would be good to add a test that makes sure that this happens exactly once. I'll add one on a unit test level

**Comment by WolframHempel** [comment]
@yasserf Looks good, I've added some unit tests as well. Could you have a last look and merge if happy

**Comment by yasserf** [comment]
looks good
