### PR TITLE
fix: Invalid remote wins merge conflicts

### LINKED ISSUE #224: merge with local wins is never sent to server
As discussed in #214. Because `set` equality check traps the update.

### PR DESCRIPTION
**Pull request by yasserf**
When the strategy is remote wins and the content is identical, we expect that
the server version number is taken and no actual merge conflict occurs

Fixes #224

### CODE REVIEW

File: src/record/record.js [hunk 1]
```diff
@@ -431,7 +432,8 @@ Record.prototype._onRecordRecovered = function (remoteVersion, remoteData, messa
 
     const oldValue = this._$data
     const newValue = jsonPath.set(oldValue, undefined, data, false)
-    if (oldValue === newValue) {
+
+    if (utils.deepEquals(oldValue, remoteData)) {
       return
```
Comment (ronag) [inline src/record/record.js]: This shouldn't be required... if `deepEquals` and `oldValue === newValue` differs then there is a bug in `jsonPath.set` and we should have a unit test for that added..

**Comment by yasserf** [comment]
@ronag it said you made a comment but I can't see it anywhere =D

I'm okay with changing the implementation, the pain was getting the tests correct. It become obviously wrong when I noticed I was getting permission issues when my connection dropped and it was trying to tell the server it accepted.. the server data when it didn't have write access.
